---
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    uses: frontierdigital/shared-workflows/.github/workflows/terraform-workload.yml@v0.0.1-pre.cb3f525
    with:
      workloadName: rancher-cluster
    secrets:
      armClientId: ${{ secrets.ARM_CLIENT_ID }}
      armClientSecret: ${{ secrets.ARM_CLIENT_SECRET }}
